name: Moritz Krog
favicon: null
layout_spectrum: 0.76081
style: A1
title: Moritz Krog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#9fbf3b'
    - '#99792f'
    - '#1071ff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
